In [1]:
import pandas as pd

In [2]:
train_dat = pd.read_csv('train.csv')

In [33]:
train_dat.dtypes

session_id          int64
index               int64
elapsed_time        int64
event_name         object
name               object
level               int64
page              float64
room_coor_x       float64
room_coor_y       float64
screen_coor_x     float64
screen_coor_y     float64
hover_duration    float64
text               object
fqid               object
room_fqid          object
text_fqid          object
fullscreen          int64
hq                  int64
music               int64
level_group        object
dtype: object

In [4]:
len(train_dat.index.unique())

26296946

In [7]:
train_dat.event_name.unique()

array(['cutscene_click', 'person_click', 'navigate_click',
       'observation_click', 'notification_click', 'object_click',
       'object_hover', 'map_hover', 'map_click', 'checkpoint',
       'notebook_click'], dtype=object)

In [10]:
train_dat.name.unique()

array(['basic', 'undefined', 'close', 'open', 'prev', 'next'],
      dtype=object)

In [13]:
train_dat[['event_name', 'name']].drop_duplicates().sort_values(['event_name'])

event_name       name
164           checkpoint      basic
0         cutscene_click      basic
1016           map_click      basic
232            map_click      close
129            map_click  undefined
127            map_hover      basic
10        navigate_click  undefined
2226      notebook_click       prev
941       notebook_click       open
942       notebook_click      close
1080      notebook_click      basic
2227      notebook_click       next
26    notification_click      basic
50          object_click      basic
27          object_click      close
49          object_hover      basic
87          object_hover  undefined
13     observation_click      basic
1           person_click      basic

In [21]:
train_dat[['event_name', 'level']].drop_duplicates().sort_values(['level'])


event_name  level
0          cutscene_click      0
1            person_click      0
10         navigate_click      0
13      observation_click      0
26     notification_click      0
...                   ...    ...
880            checkpoint     22
874        navigate_click     22
877             map_hover     22
33764        person_click     22
878             map_click     22

[210 rows x 2 columns]

In [20]:
train_dat[['event_name', 'page']].drop_duplicates()

event_name  page
0         cutscene_click   NaN
1           person_click   NaN
10        navigate_click   NaN
13     observation_click   NaN
26    notification_click   NaN
27          object_click   NaN
49          object_hover   NaN
127            map_hover   NaN
129            map_click   NaN
164           checkpoint   NaN
941       notebook_click   0.0
1079      notebook_click   1.0
1283      notebook_click   3.0
1474      notebook_click   4.0
2224      notebook_click   5.0
2459      notebook_click   6.0
4752      notebook_click   2.0

In [24]:
train_dat.loc[pd.isnull(train_dat.room_coor_x)].event_name.unique()

array(['object_hover', 'map_hover', 'checkpoint'], dtype=object)

In [26]:
train_dat[['room_coor_x', 'screen_coor_x', 'room_coor_y', 'screen_coor_y']]

room_coor_x  screen_coor_x  room_coor_y  screen_coor_y
0         -413.991405          380.0  -159.314686          494.0
1         -413.991405          380.0  -159.314686          494.0
2         -413.991405          380.0  -159.314686          494.0
3         -413.991405          380.0  -159.314686          494.0
4         -412.991405          381.0  -159.314686          494.0
...               ...            ...          ...            ...
26296941   343.887291          483.0    36.701026          273.0
26296942   332.696070          545.0   141.493178          221.0
26296943   369.912859          611.0   140.569205          217.0
26296944   252.299653          526.0   123.805889          232.0
26296945          NaN            NaN          NaN            NaN

[26296946 rows x 4 columns]

In [29]:
train_dat.isna().sum()

session_id               0
index                    0
elapsed_time             0
event_name               0
name                     0
level                    0
page              25732402
room_coor_x        2073272
room_coor_y        2073272
screen_coor_x      2073272
screen_coor_y      2073272
hover_duration    24294702
text              16679807
fqid               8274415
room_fqid                0
text_fqid         16679702
fullscreen               0
hq                       0
music                    0
level_group              0
dtype: int64

In [28]:
train_dat[['text']].isna().sum()

text    16679807
dtype: int64

In [30]:
train_dat.loc[pd.notnull(train_dat.hover_duration), :].event_name.unique()

array(['object_hover', 'map_hover'], dtype=object)

In [31]:
train_dat.hq.unique()

array([0, 1])

In [35]:
train_dat.loc[pd.isnull(train_dat.fqid)].event_name.unique()

array(['navigate_click', 'notification_click', 'map_click',
       'notebook_click'], dtype=object)

In [36]:
train_dat.event_name.unique()


array(['cutscene_click', 'person_click', 'navigate_click',
       'observation_click', 'notification_click', 'object_click',
       'object_hover', 'map_hover', 'map_click', 'checkpoint',
       'notebook_click'], dtype=object)

In [37]:
len(train_dat.room_fqid.unique())

19

In [38]:
train_dat.room_fqid.unique()

array(['tunic.historicalsociety.closet',
       'tunic.historicalsociety.basement',
       'tunic.historicalsociety.entry',
       'tunic.historicalsociety.collection',
       'tunic.historicalsociety.stacks', 'tunic.kohlcenter.halloffame',
       'tunic.capitol_0.hall', 'tunic.historicalsociety.closet_dirty',
       'tunic.historicalsociety.frontdesk',
       'tunic.humanecology.frontdesk', 'tunic.drycleaner.frontdesk',
       'tunic.library.frontdesk', 'tunic.library.microfiche',
       'tunic.capitol_1.hall', 'tunic.historicalsociety.cage',
       'tunic.historicalsociety.collection_flag', 'tunic.wildlife.center',
       'tunic.flaghouse.entry', 'tunic.capitol_2.hall'], dtype=object)

In [40]:
train_dat[['room_fqid', 'event_name']].drop_duplicates().sort_values(['room_fqid'])

room_fqid          event_name
163     tunic.capitol_0.hall      navigate_click
25555   tunic.capitol_0.hall      cutscene_click
166     tunic.capitol_0.hall        person_click
172     tunic.capitol_0.hall           map_hover
173     tunic.capitol_0.hall           map_click
...                      ...                 ...
733    tunic.wildlife.center        object_hover
735    tunic.wildlife.center        object_click
736    tunic.wildlife.center  notification_click
770    tunic.wildlife.center           map_hover
774    tunic.wildlife.center           map_click

[131 rows x 2 columns]

In [139]:
train_dat[['room_fqid', 'event_name']].drop_duplicates().groupby(['room_fqid'])[['event_name']].count()

event_name
room_fqid                                          
tunic.capitol_0.hall                              6
tunic.capitol_1.hall                              6
tunic.capitol_2.hall                              6
tunic.drycleaner.frontdesk                        9
tunic.flaghouse.entry                             8
tunic.historicalsociety.basement                  5
tunic.historicalsociety.cage                      5
tunic.historicalsociety.closet                    8
tunic.historicalsociety.closet_dirty              5
tunic.historicalsociety.collection                7
tunic.historicalsociety.collection_flag           3
tunic.historicalsociety.entry                    10
tunic.historicalsociety.frontdesk                 4
tunic.historicalsociety.stacks                    6
tunic.humanecology.frontdesk                      9
tunic.kohlcenter.halloffame                       9
tunic.library.frontdesk                          10
tunic.library.microfiche                          6
tunic.wildlife.center                             9

In [42]:
train_dat.level_group.unique()

array(['0-4', '5-12', '13-22'], dtype=object)

In [3]:
correct_label = pd.read_csv('train_labels.csv')

In [81]:
correct_label.dtypes

session_id    object
correct        int64
dtype: object

In [45]:
train_dat.head(5)

session_id  index  elapsed_time      event_name   name  level  page  \
0  20090312431273200      0             0  cutscene_click  basic      0   NaN   
1  20090312431273200      1          1323    person_click  basic      0   NaN   
2  20090312431273200      2           831    person_click  basic      0   NaN   
3  20090312431273200      3          1147    person_click  basic      0   NaN   
4  20090312431273200      4          1863    person_click  basic      0   NaN   

   room_coor_x  room_coor_y  screen_coor_x  screen_coor_y  hover_duration  \
0  -413.991405  -159.314686          380.0          494.0             NaN   
1  -413.991405  -159.314686          380.0          494.0             NaN   
2  -413.991405  -159.314686          380.0          494.0             NaN   
3  -413.991405  -159.314686          380.0          494.0             NaN   
4  -412.991405  -159.314686          381.0          494.0             NaN   

                            text    fqid                       room_fqid  \
0                      undefined   intro  tunic.historicalsociety.closet   
1  Whatcha doing over there, Jo?  gramps  tunic.historicalsociety.closet   
2         Just talking to Teddy.  gramps  tunic.historicalsociety.closet   
3     I gotta run to my meeting!  gramps  tunic.historicalsociety.closet   
4            Can I come, Gramps?  gramps  tunic.historicalsociety.closet   

                                           text_fqid  fullscreen  hq  music  \
0               tunic.historicalsociety.closet.intro           0   0      1   
1  tunic.historicalsociety.closet.gramps.intro_0_...           0   0      1   
2  tunic.historicalsociety.closet.gramps.intro_0_...           0   0      1   
3  tunic.historicalsociety.closet.gramps.intro_0_...           0   0      1   
4  tunic.historicalsociety.closet.gramps.intro_0_...           0   0      1   

  level_group  
0         0-4  
1         0-4  
2         0-4  
3         0-4  
4         0-4

In [46]:
correct_label.session_id[0].split('_')

['20090312431273200', 'q1']

In [4]:
correct_label['quarter'] = correct_label.session_id.apply(lambda x: x.split('_')[1].replace('q', ''))

In [5]:
correct_label['session_id_new'] = correct_label.session_id.apply(lambda x: x.split('_')[0])

In [49]:
correct_label.quarter.unique()

array(['q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11',
       'q12', 'q13', 'q14', 'q15', 'q16', 'q17', 'q18'], dtype=object)

In [6]:
correct_label['level'] = correct_label.quarter.astype('int') - 1

In [61]:
correct_label.loc[correct_label.session_id_new == '20090312431273200', :]


session_id  correct quarter     session_id_new  level
0        20090312431273200_q1        1       1  20090312431273200      0
23562    20090312431273200_q2        1       2  20090312431273200      1
47124    20090312431273200_q3        1       3  20090312431273200      2
70686    20090312431273200_q4        1       4  20090312431273200      3
94248    20090312431273200_q5        1       5  20090312431273200      4
117810   20090312431273200_q6        1       6  20090312431273200      5
141372   20090312431273200_q7        1       7  20090312431273200      6
164934   20090312431273200_q8        1       8  20090312431273200      7
188496   20090312431273200_q9        1       9  20090312431273200      8
212058  20090312431273200_q10        1      10  20090312431273200      9
235620  20090312431273200_q11        1      11  20090312431273200     10
259182  20090312431273200_q12        1      12  20090312431273200     11
282744  20090312431273200_q13        0      13  20090312431273200     12
306306  20090312431273200_q14        1      14  20090312431273200     13
329868  20090312431273200_q15        1      15  20090312431273200     14
353430  20090312431273200_q16        0      16  20090312431273200     15
376992  20090312431273200_q17        1      17  20090312431273200     16
400554  20090312431273200_q18        1      18  20090312431273200     17

In [7]:
correct_label['session_id_new'] = correct_label['session_id_new'].astype('int')


In [66]:
correct_label.columns

Index(['session_id', 'correct', 'quarter', 'session_id_new', 'level'], dtype='object')

In [8]:
correct_label.columns = ['session_id_old', 'correct', 'quarter', 'session_id', 'level']


In [58]:
train_dat.loc[train_dat.session_id == 20090312431273200, :][['level', 'level_group']].drop_duplicates()

level level_group
0        0         0-4
28       1         0-4
60       2         0-4
99       3         0-4
152      4         0-4
165      5        5-12
183      6        5-12
264      7        5-12
308      8        5-12
344      9        5-12
379     10        5-12
394     11        5-12
451     12        5-12
461     13       13-22
501     14       13-22
516     15       13-22
558     16       13-22
600     17       13-22
634     18       13-22
767     19       13-22
800     20       13-22
830     21       13-22
874     22       13-22

In [9]:
merge_dat = pd.merge(train_dat, correct_label[['level', 'session_id', 'correct']], how = 'left', on = ['session_id', 'level'])


In [10]:
analy_dat = merge_dat.loc[pd.notnull(merge_dat.correct)]

In [11]:
analy_dat.correct = analy_dat.correct.astype('int')

/Users/eunjeongahn/opt/anaconda3/envs/BrRetention/lib/python3.8/site-packages/pandas/core/generic.py:5516: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [78]:
check = analy_dat[['session_id', 'level']].drop_duplicates().groupby(['session_id']).count()

In [83]:
check.loc[check.level < 18]

level
session_id              
20090316190523732     17
20100007445515820     17
20100014211946468     17
20100018421509572     17
20100115005512812     17
...                  ...
22090219034194660     17
22090313443250680     17
22090320210258944     17
22090413294967440     17
22090417091699070     17

[561 rows x 1 columns]

In [69]:
merge_dat.isna().sum()

session_id               0
index                    0
elapsed_time             0
event_name               0
name                     0
level                    0
page              25732402
room_coor_x        2073272
room_coor_y        2073272
screen_coor_x      2073272
screen_coor_y      2073272
hover_duration    24294702
text              16679807
fqid               8274415
room_fqid                0
text_fqid         16679702
fullscreen               0
hq                       0
music                    0
level_group              0
correct            8374539
dtype: int64

In [62]:
test_dat = pd.read_csv('test.csv')

In [63]:
test_dat.head()

session_id  index  elapsed_time      event_name   name  level  page  \
0  20090109393214576      0             0  cutscene_click  basic      0   NaN   
1  20090109393214576      1          1965    person_click  basic      0   NaN   
2  20090109393214576      2          3614    person_click  basic      0   NaN   
3  20090109393214576      3          5330    person_click  basic      0   NaN   
4  20090109393214576      4          6397    person_click  basic      0   NaN   

   room_coor_x  room_coor_y  screen_coor_x  ...  hover_duration  \
0  -413.991405    75.685314          380.0  ...             NaN   
1  -105.991405   -63.314686          688.0  ...             NaN   
2  -418.991405    47.685314          375.0  ...             NaN   
3  -110.991405   -57.314686          683.0  ...             NaN   
4  -110.991405   -57.314686          683.0  ...             NaN   

                            text    fqid                       room_fqid  \
0                      undefined   intro  tunic.historicalsociety.closet   
1  Whatcha doing over there, Jo?  gramps  tunic.historicalsociety.closet   
2         Just talking to Teddy.  gramps  tunic.historicalsociety.closet   
3     I gotta run to my meeting!  gramps  tunic.historicalsociety.closet   
4            Can I come, Gramps?  gramps  tunic.historicalsociety.closet   

                                           text_fqid fullscreen  hq  music  \
0               tunic.historicalsociety.closet.intro          0   0      1   
1  tunic.historicalsociety.closet.gramps.intro_0_...          0   0      1   
2  tunic.historicalsociety.closet.gramps.intro_0_...          0   0      1   
3  tunic.historicalsociety.closet.gramps.intro_0_...          0   0      1   
4  tunic.historicalsociety.closet.gramps.intro_0_...          0   0      1   

   level_group session_level  
0          0-4             0  
1          0-4             0  
2          0-4             0  
3          0-4             0  
4          0-4             0  

[5 rows x 21 columns]

In [140]:
merge_dat.columns

Index(['session_id', 'index', 'elapsed_time', 'event_name', 'name', 'level',
       'page', 'room_coor_x', 'room_coor_y', 'screen_coor_x', 'screen_coor_y',
       'hover_duration', 'text', 'fqid', 'room_fqid', 'text_fqid',
       'fullscreen', 'hq', 'music', 'level_group', 'correct', 'rood_lv2',
       'rood_lv3'],
      dtype='object')

In [141]:
merge_dat[['rood_lv2', 'event_name']].drop_duplicates().sort_values(['rood_lv2'])

rood_lv2         event_name
164    capitol_0         checkpoint
25555  capitol_0     cutscene_click
173    capitol_0          map_click
172    capitol_0          map_hover
166    capitol_0       person_click
...          ...                ...
735     wildlife       object_click
733     wildlife       object_hover
677     wildlife       person_click
674     wildlife  observation_click
671     wildlife     navigate_click

[82 rows x 2 columns]

In [91]:
pd.crosstab(merge_dat.level, merge_dat.correct)

correct     0.0      1.0
level                   
0        199838   489154
1         18506   708084
2         71873   920742
3        267096   877672
4        202202   225838
5        183484   484704
6        604206  1513590
7        515172   763035
8        246579   642005
9        600518   537230
10       165589   283550
11       326987  1610221
12       275857    91511
13       254095   569780
14       298723   252106
15       356644   862853
16       406444   888638
17        76522  1131359

In [92]:
import scipy.stats as stats

In [142]:
stats.chi2_contingency(pd.crosstab(merge_dat.level, merge_dat.correct))[1]


0.0

In [94]:
stats.chi2_contingency(pd.crosstab(merge_dat.music, merge_dat.correct))


(2360.6485753348175,
 0.0,
 1,
 array([[  360072.46167409,   912696.53832591],
        [ 4710262.53832591, 11939375.46167409]]))

In [95]:
pd.crosstab(merge_dat.music, merge_dat.correct)


correct      0.0       1.0
music                     
0         336276    936493
1        4734059  11915579

In [96]:
pd.crosstab(merge_dat.event_name, merge_dat.correct)


correct                 0.0      1.0
event_name                          
checkpoint            27938    19457
cutscene_click       511636  1978234
map_click            109046   211045
map_hover            156728   330658
navigate_click      2327953  5408469
notebook_click       111664   249081
notification_click   107956   345384
object_click         478180  1098090
object_hover         198945   477382
observation_click     48015   114065
person_click         992274  2620207

In [97]:
stats.chi2_contingency(pd.crosstab(merge_dat.event_name, merge_dat.correct))


(127494.20584045089,
 0.0,
 10,
 array([[  13408.27308101,   33986.72691899],
        [ 704396.17884194, 1785473.82115806],
        [  90555.28091093,  229535.71908907],
        [ 137883.839727  ,  349502.160273  ],
        [2188670.93250198, 5547751.06749802],
        [ 102056.49272305,  258688.50727695],
        [ 128252.06284513,  325087.93715487],
        [ 445934.35192327, 1130335.64807673],
        [ 191336.15588269,  484990.84411731],
        [  45853.21027471,  116226.78972529],
        [1021988.2212883 , 2590492.7787117 ]]))

In [114]:
pd.crosstab(merge_dat.fullscreen, merge_dat.correct)


correct         0.0       1.0
fullscreen                   
0           4389807  11082873
1            680528   1769199

In [113]:
stats.chi2_contingency(pd.crosstab(merge_dat.fullscreen, merge_dat.correct))


(364.82298854195324,
 2.5084831590188503e-81,
 1,
 array([[ 4377295.46861646, 11095384.53138353],
        [  693039.53138354,  1756687.46861646]]))

In [115]:
pd.crosstab(merge_dat.hq, merge_dat.correct)


correct      0.0       1.0
hq                        
0        4500912  11270841
1         569423   1581231

In [116]:
stats.chi2_contingency(pd.crosstab(merge_dat.hq, merge_dat.correct))


(3962.8743912111568,
 0.0,
 1,
 array([[ 4461904.65640329, 11309848.34359671],
        [  608430.34359671,  1542223.65640329]]))

In [104]:
merge_dat.loc[merge_dat.correct == 1.0].page.unique()

array([nan,  0.,  1.,  3.,  4.,  2.])

In [105]:
merge_dat.loc[merge_dat.correct == 0.0].page.unique()


array([nan,  3.,  1.,  2.,  0.,  4.])

In [109]:
stats.ttest_ind(merge_dat.loc[(merge_dat.correct == 1.0)&pd.notnull(merge_dat.hover_duration)].hover_duration,
                merge_dat.loc[(merge_dat.correct == 0.0) & pd.notnull(merge_dat.hover_duration)].hover_duration)


Ttest_indResult(statistic=0.8953840101289849, pvalue=0.3705820304698789)

In [111]:
stats.ttest_ind(merge_dat.loc[(merge_dat.correct == 1.0) & pd.notnull(merge_dat.page)].page,
                merge_dat.loc[(merge_dat.correct == 0.0) & pd.notnull(merge_dat.page)].page)


Ttest_indResult(statistic=-39.98093090014731, pvalue=0.0)

In [112]:
stats.ttest_ind(merge_dat.loc[(merge_dat.correct == 1.0) & pd.notnull(merge_dat.elapsed_time)].elapsed_time,
                merge_dat.loc[(merge_dat.correct == 0.0) & pd.notnull(merge_dat.elapsed_time)].elapsed_time)


Ttest_indResult(statistic=-35.85513931401155, pvalue=1.565081373886043e-281)

In [118]:
import numpy as np

In [126]:
print('The elapsed_time of correct is : ', round(np.mean(merge_dat.loc[(merge_dat.correct == 1.0) &
      pd.notnull(merge_dat.elapsed_time)].elapsed_time)*1.66667e-5, 2))


print('The elapsed_time of incorrect is : ', round(np.mean(merge_dat.loc[(merge_dat.correct == 0.0) &
      pd.notnull(merge_dat.elapsed_time)].elapsed_time)*1.66667e-5, 2))

print('The differntiattion (minutes) of elapsed_time between correct and incorrect is : ' , round(abs(np.mean(merge_dat.loc[(merge_dat.correct == 0.0) &
      pd.notnull(merge_dat.elapsed_time)].elapsed_time) - np.mean(merge_dat.loc[(merge_dat.correct == 1.0) &
                                                                                pd.notnull(merge_dat.elapsed_time)].elapsed_time))*1.66667e-5, 2))


The elapsed_time of correct is :  41.92
The elapsed_time of incorrect is :  50.23
The differntiattion (minutes) of elapsed_time between correct and incorrect is :  8.31


In [128]:
merge_dat.room_fqid.unique()


array(['tunic.historicalsociety.closet',
       'tunic.historicalsociety.basement',
       'tunic.historicalsociety.entry',
       'tunic.historicalsociety.collection',
       'tunic.historicalsociety.stacks', 'tunic.kohlcenter.halloffame',
       'tunic.capitol_0.hall', 'tunic.historicalsociety.closet_dirty',
       'tunic.historicalsociety.frontdesk',
       'tunic.humanecology.frontdesk', 'tunic.drycleaner.frontdesk',
       'tunic.library.frontdesk', 'tunic.library.microfiche',
       'tunic.capitol_1.hall', 'tunic.historicalsociety.cage',
       'tunic.historicalsociety.collection_flag', 'tunic.wildlife.center',
       'tunic.flaghouse.entry', 'tunic.capitol_2.hall'], dtype=object)

In [12]:
merge_dat['room_lv2'] = merge_dat.room_fqid.apply(lambda x: x.split('.')[1])

In [13]:
merge_dat['room_lv3'] = merge_dat.room_fqid.apply(lambda x: x.split('.')[2])


In [131]:
pd.crosstab(merge_dat.rood_lv2, merge_dat.correct)


correct                0.0      1.0
rood_lv2                           
capitol_0           128372   288097
capitol_1           157079   288490
capitol_2            20614    70977
drycleaner          332103   621981
historicalsociety  2943294  9096223
humanecology        469016   794359
kohlcenter          336327   712540
library             683530   979405

In [133]:
stats.chi2_contingency(pd.crosstab(merge_dat.rood_lv2, merge_dat.correct))


(311672.3920076617,
 0.0,
 7,
 array([[ 117821.0798982 ,  298647.9201018 ],
        [ 126053.60963039,  319515.39036961],
        [  25911.53370108,   65679.46629892],
        [ 269914.94491449,  684169.05508551],
        [3406037.1705762 , 8633479.8294238 ],
        [ 357414.85396604,  905960.14603396],
        [ 296729.51074289,  752137.48925711],
        [ 470452.29657071, 1192482.70342929]]))

In [132]:
pd.crosstab(merge_dat.rood_lv3, merge_dat.correct)


correct              0.0      1.0
rood_lv3                         
basement          273730   853493
cage              728768  1530823
closet            214490   642783
closet_dirty      404685  1075094
collection        123423   833977
collection_flag    19848   239443
entry             529075  1889941
frontdesk        1602408  3308711
hall              306065   647564
halloffame        336327   712540
microfiche        259699   243595
stacks            271817   874108

In [134]:
stats.chi2_contingency(pd.crosstab(merge_dat.rood_lv3, merge_dat.correct))


(453347.738301407,
 0.0,
 11,
 array([[ 318896.79939224,  808326.20060776],
        [ 639249.1439897 , 1620341.8560103 ],
        [ 242526.64814804,  614746.35185196],
        [ 418636.5846934 , 1061142.4153066 ],
        [ 270853.05723723,  686546.94276277],
        [  73354.66896188,  185936.33103812],
        [ 684351.24201565, 1734664.75798435],
        [1389379.14727999, 3521739.85272001],
        [ 269786.22322967,  683842.77677033],
        [ 296729.51074289,  752137.48925711],
        [ 142384.28931393,  360909.71068607],
        [ 324187.68499538,  821737.31500462]]))

In [135]:
merge_dat.loc[merge_dat.index == 1]

session_id  index  elapsed_time    event_name   name  level  page  \
1  20090312431273200      1          1323  person_click  basic      0   NaN   

   room_coor_x  room_coor_y  screen_coor_x  ...    fqid  \
1  -413.991405  -159.314686          380.0  ...  gramps   

                        room_fqid  \
1  tunic.historicalsociety.closet   

                                           text_fqid fullscreen hq music  \
1  tunic.historicalsociety.closet.gramps.intro_0_...          0  0     1   

   level_group  correct           rood_lv2 rood_lv3  
1          0-4      1.0  historicalsociety   closet  

[1 rows x 23 columns]

In [143]:
merge_dat.loc[pd.isnull(merge_dat.page)&pd.isnull(merge_dat.hover_duration)].event_name.unique()

array(['cutscene_click', 'person_click', 'navigate_click',
       'observation_click', 'notification_click', 'object_click',
       'map_click', 'checkpoint'], dtype=object)

In [145]:
merge_dat.loc[pd.isnull(merge_dat.elapsed_time)].event_name.unique()


array([], dtype=object)

In [146]:
merge_dat.columns

Index(['session_id', 'index', 'elapsed_time', 'event_name', 'name', 'level',
       'page', 'room_coor_x', 'room_coor_y', 'screen_coor_x', 'screen_coor_y',
       'hover_duration', 'text', 'fqid', 'room_fqid', 'text_fqid',
       'fullscreen', 'hq', 'music', 'level_group', 'correct', 'rood_lv2',
       'rood_lv3'],
      dtype='object')

In [14]:
train_data = merge_dat[['level', 'music', 'event_name', 'fullscreen',
                       'hq', 'room_lv3', 'page', 'elapsed_time', 'correct']]


In [23]:
train_columns = ['level', 'music', 'event_name', 'fullscreen',
                 'hq', 'room_lv3', 'page', 'elapsed_time']


In [22]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier


In [47]:
train_data = train_data.loc[pd.notnull(train_data.correct)].reset_index(drop=True)

In [48]:
X_train, X_test, y_train, y_test = train_test_split(train_data[train_columns], train_data['correct'],
                                                    test_size=0.25, stratify=train_data['correct'], random_state=32)


In [49]:
train_idx = X_train.index
test_idx = X_test.index

In [33]:
cate_col = ['event_name', 'room_lv3']


In [34]:
dummy_dat = pd.get_dummies(train_data[cate_col])

In [36]:
finl_dat = pd.concat([train_data[['level', 'music', 'fullscreen', 'hq', 'page', 'elapsed_time', 'correct']], dummy_dat], axis = 1)


In [37]:
finl_dat.columns

Index(['level', 'music', 'fullscreen', 'hq', 'page', 'elapsed_time', 'correct',
       'event_name_checkpoint', 'event_name_cutscene_click',
       'event_name_map_click', 'event_name_map_hover',
       'event_name_navigate_click', 'event_name_notebook_click',
       'event_name_notification_click', 'event_name_object_click',
       'event_name_object_hover', 'event_name_observation_click',
       'event_name_person_click', 'room_lv3_basement', 'room_lv3_cage',
       'room_lv3_closet', 'room_lv3_closet_dirty', 'room_lv3_collection',
       'room_lv3_collection_flag', 'room_lv3_entry', 'room_lv3_frontdesk',
       'room_lv3_hall', 'room_lv3_halloffame', 'room_lv3_microfiche',
       'room_lv3_stacks'],
      dtype='object')

In [39]:
finl_col = ['level', 'music', 'fullscreen', 'hq', 'page', 'elapsed_time',
            'event_name_checkpoint', 'event_name_cutscene_click',
            'event_name_map_click', 'event_name_map_hover',
            'event_name_navigate_click', 'event_name_notebook_click',
            'event_name_notification_click', 'event_name_object_click',
            'event_name_object_hover', 'event_name_observation_click',
            'event_name_person_click', 'room_lv3_basement', 'room_lv3_cage',
            'room_lv3_closet', 'room_lv3_closet_dirty', 'room_lv3_collection',
            'room_lv3_collection_flag', 'room_lv3_entry', 'room_lv3_frontdesk',
            'room_lv3_hall', 'room_lv3_halloffame', 'room_lv3_microfiche',
            'room_lv3_stacks']


In [38]:
from sklearn.preprocessing import StandardScaler

std = StandardScaler()


In [50]:
X_train = finl_dat.iloc[train_idx][finl_col]
X_test = finl_dat.iloc[test_idx][finl_col]


In [51]:
X_test = finl_dat.iloc[test_idx][finl_col]


In [53]:
std.fit(X_train)
X_train_scaled = std.transform(X_train)
std.fit(X_test)
X_test_scaled = std.transform(X_test)


In [54]:
model = XGBClassifier(n_estimators=500, learning_rate=0.2,
                      max_depth=4, random_state=32)


In [55]:
model.fit(X_train, y_train)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.2, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=500, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=32, ...)

In [56]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)  # 예측 라벨(0과 1로 예측)

# 예측 라벨과 실제 라벨 사이의 정확도 측정
accuracy_score(y_pred, y_test)  # 0.7847533632286996


0.7367800130428902

In [57]:
feature_importance = pd.DataFrame(model.feature_importances_.reshape(
    (1, -1)), columns=X_train.columns, index=['feature_importance'])
feature_importance.transpose().sort_values(
    ['feature_importance'], ascending=False)


level     music  fullscreen        hq      page  \
feature_importance  0.35627  0.008798    0.007289  0.010499  0.004947   

                    elapsed_time  event_name_checkpoint  \
feature_importance      0.017209               0.014321   

                    event_name_cutscene_click  event_name_map_click  \
feature_importance                    0.09766              0.002283   

                    event_name_map_hover  ...  room_lv3_closet  \
feature_importance              0.003001  ...          0.00638   

                    room_lv3_closet_dirty  room_lv3_collection  \
feature_importance               0.010219             0.011391   

                    room_lv3_collection_flag  room_lv3_entry  \
feature_importance                  0.006552        0.032356   

                    room_lv3_frontdesk  room_lv3_hall  room_lv3_halloffame  \
feature_importance             0.01642       0.024891             0.027131   

                    room_lv3_microfiche  room_lv3_stacks  
feature_importance              0.20938         0.006126  

[1 rows x 29 columns]

In [61]:
feature_importance.transpose().sort_values(['feature_importance'], ascending=False)


feature_importance
level                                    0.356270
room_lv3_microfiche                      0.209380
event_name_cutscene_click                0.097660
room_lv3_entry                           0.032356
event_name_navigate_click                0.027975
room_lv3_halloffame                      0.027131
room_lv3_hall                            0.024891
event_name_notification_click            0.021224
room_lv3_basement                        0.021131
event_name_person_click                  0.017727
elapsed_time                             0.017209
room_lv3_frontdesk                       0.016420
event_name_object_click                  0.014965
event_name_checkpoint                    0.014321
room_lv3_cage                            0.013688
room_lv3_collection                      0.011391
hq                                       0.010499
room_lv3_closet_dirty                    0.010219
music                                    0.008798
fullscreen                               0.007289
event_name_object_hover                  0.006986
room_lv3_collection_flag                 0.006552
room_lv3_closet                          0.006380
room_lv3_stacks                          0.006126
page                                     0.004947
event_name_observation_click             0.003178
event_name_map_hover                     0.003001
event_name_map_click                     0.002283
event_name_notebook_click                0.000000

In [62]:
train_dat.head()

session_id  index  elapsed_time      event_name   name  level  page  \
0  20090312431273200      0             0  cutscene_click  basic      0   NaN   
1  20090312431273200      1          1323    person_click  basic      0   NaN   
2  20090312431273200      2           831    person_click  basic      0   NaN   
3  20090312431273200      3          1147    person_click  basic      0   NaN   
4  20090312431273200      4          1863    person_click  basic      0   NaN   

   room_coor_x  room_coor_y  screen_coor_x  screen_coor_y  hover_duration  \
0  -413.991405  -159.314686          380.0          494.0             NaN   
1  -413.991405  -159.314686          380.0          494.0             NaN   
2  -413.991405  -159.314686          380.0          494.0             NaN   
3  -413.991405  -159.314686          380.0          494.0             NaN   
4  -412.991405  -159.314686          381.0          494.0             NaN   

                            text    fqid                       room_fqid  \
0                      undefined   intro  tunic.historicalsociety.closet   
1  Whatcha doing over there, Jo?  gramps  tunic.historicalsociety.closet   
2         Just talking to Teddy.  gramps  tunic.historicalsociety.closet   
3     I gotta run to my meeting!  gramps  tunic.historicalsociety.closet   
4            Can I come, Gramps?  gramps  tunic.historicalsociety.closet   

                                           text_fqid  fullscreen  hq  music  \
0               tunic.historicalsociety.closet.intro           0   0      1   
1  tunic.historicalsociety.closet.gramps.intro_0_...           0   0      1   
2  tunic.historicalsociety.closet.gramps.intro_0_...           0   0      1   
3  tunic.historicalsociety.closet.gramps.intro_0_...           0   0      1   
4  tunic.historicalsociety.closet.gramps.intro_0_...           0   0      1   

  level_group  
0         0-4  
1         0-4  
2         0-4  
3         0-4  
4         0-4

In [63]:
correct_label.head()

session_id_old  correct quarter         session_id  level
0  20090312431273200_q1        1       1  20090312431273200      0
1  20090312433251036_q1        0       1  20090312433251036      0
2  20090312455206810_q1        1       1  20090312455206810      0
3  20090313091715820_q1        0       1  20090313091715820      0
4  20090313571836404_q1        1       1  20090313571836404      0

In [65]:
correct_label.level.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [64]:
merge_dat.head() #aggregation

session_id  index  elapsed_time      event_name   name  level  page  \
0  20090312431273200      0             0  cutscene_click  basic      0   NaN   
1  20090312431273200      1          1323    person_click  basic      0   NaN   
2  20090312431273200      2           831    person_click  basic      0   NaN   
3  20090312431273200      3          1147    person_click  basic      0   NaN   
4  20090312431273200      4          1863    person_click  basic      0   NaN   

   room_coor_x  room_coor_y  screen_coor_x  ...    fqid  \
0  -413.991405  -159.314686          380.0  ...   intro   
1  -413.991405  -159.314686          380.0  ...  gramps   
2  -413.991405  -159.314686          380.0  ...  gramps   
3  -413.991405  -159.314686          380.0  ...  gramps   
4  -412.991405  -159.314686          381.0  ...  gramps   

                        room_fqid  \
0  tunic.historicalsociety.closet   
1  tunic.historicalsociety.closet   
2  tunic.historicalsociety.closet   
3  tunic.historicalsociety.closet   
4  tunic.historicalsociety.closet   

                                           text_fqid fullscreen hq music  \
0               tunic.historicalsociety.closet.intro          0  0     1   
1  tunic.historicalsociety.closet.gramps.intro_0_...          0  0     1   
2  tunic.historicalsociety.closet.gramps.intro_0_...          0  0     1   
3  tunic.historicalsociety.closet.gramps.intro_0_...          0  0     1   
4  tunic.historicalsociety.closet.gramps.intro_0_...          0  0     1   

   level_group  correct           room_lv2 room_lv3  
0          0-4      1.0  historicalsociety   closet  
1          0-4      1.0  historicalsociety   closet  
2          0-4      1.0  historicalsociety   closet  
3          0-4      1.0  historicalsociety   closet  
4          0-4      1.0  historicalsociety   closet  

[5 rows x 23 columns]

In [66]:
len(finl_dat.columns)

30

In [68]:
len(merge_dat.room_lv3.unique())

13